version: '3'

services:
  amqp-service:
    image: rabbitmq:3-management
    ports:
    - 15672:15672
    - 5672:5672

  gateway-service:
    image: navsinha5/gateway
    ports:
    - 8443:8443
    depends_on:
      - amqp-service

  storage-service:
    image: navsinha5/storage
    ports:
    - 7443:7443
    depends_on:
      - amqp-service
      - gateway-service